### ISSUE TITLE
Catch double charset evasion

### ISSUE THREAD

**Issue by theseion** [coreruleset/coreruleset#3692]
We have a test case (920480) for double charset evasion, which is currently commented because that functionality doesn't exist yet:

```yaml
  - test_id: 12
    stages:
      - input:
          dest_addr: "127.0.0.1"
          port: 80
          method: "POST"
          headers:
              User-Agent: "OWASP CRS test agent"
              Host: "localhost"
              # double charset may cause evasion
              Content-Type: "application/x-www-form-urlencoded;charset=utf-8;charset=ibm037"
          data: "test=value"
        output:
          log:
            expect_ids: [920480]
```

Implement the missing functionality.
