### ISSUE TITLE
Dir listing is not getting blocked

### ISSUE THREAD

**Issue by justlife4x4** [coreruleset/coreruleset#3988]
Hi, Im using a docker version:

# Content of `docker-compose.yml`:

```
services:
    reverseproxy:
        container_name: reverse-proxy-nginx
        ports:
            - '80:80'
        volumes:
            - ./proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
        environment:
            - PROXY=1
        image: owasp/modsecurity-crs:nginx
        networks:
            reverse-proxy-nginx:
                aliases:
                    - reverse-proxy-nginx

    owasp-juice-shop:
        container_name: owasp-juice-shop
        image: vulnerables/web-dvwa
        ports:
            - '80'
        networks:
            reverse-proxy-nginx:
                aliases:
                    - owasp-juice-shop

networks:
    reverse-proxy-nginx:
        external: true
```

Still Im seeing 

![Image](https://github.com/user-attachments/assets/e26a932e-add9-4e6c-9b16-111507cb62a2)

Can you please tell why the rule `950-DATA-LEAK ` isnt working. Requesting speedy assistance , pls

Thanks & Regards,
@justlife4x4
